"""add_notification_settings

Revision ID: 022a54f628db
Revises: ee17bd5d5c85
Create Date: 2026-01-27 23:06:55.751742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022a54f628db'
down_revision: Union[str, Sequence[str], None] = 'ee17bd5d5c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('is_notification_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('is_notification_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_notification_enabled')
    op.drop_column('monitors', 'is_notification_enabled')
    # ### end Alembic commands ###
