"""add_pro_features

Revision ID: a76a9e0f991c
Revises: 022a54f628db
Create Date: 2026-02-05 23:24:27.018752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76a9e0f991c'
down_revision: Union[str, Sequence[str], None] = '022a54f628db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_windows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_windows_monitor_id'), 'maintenance_windows', ['monitor_id'], unique=False)
    
    op.add_column('monitors', sa.Column('check_ssl', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('monitors', sa.Column('ssl_expiry_days_threshold', sa.Integer(), nullable=False, server_default='7'))
    op.add_column('monitors', sa.Column('keyword_include', sa.String(), nullable=True))
    op.add_column('monitors', sa.Column('keyword_exclude', sa.String(), nullable=True))
    op.add_column('monitors', sa.Column('max_response_time', sa.Float(), nullable=True))
    op.add_column('monitors', sa.Column('consecutive_checks', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'consecutive_checks')
    op.drop_column('monitors', 'max_response_time')
    op.drop_column('monitors', 'keyword_exclude')
    op.drop_column('monitors', 'keyword_include')
    op.drop_column('monitors', 'ssl_expiry_days_threshold')
    op.drop_column('monitors', 'check_ssl')
    op.drop_index(op.f('ix_maintenance_windows_monitor_id'), table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    # ### end Alembic commands ###
