"""add_email_features

Revision ID: c4d72f6e4d5a
Revises: a76a9e0f991c
Create Date: 2026-02-05 23:50:02.159154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d72f6e4d5a'
down_revision: Union[str, Sequence[str], None] = 'a76a9e0f991c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_email_notification_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('email_notification_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_email_notification_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_email_notification_date')
    op.drop_column('users', 'email_notification_count')
    op.drop_column('users', 'is_email_notification_enabled')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
